// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customer": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer Service"
                ],
                "summary": "List All Customers",
                "responses": {}
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer Service"
                ],
                "summary": "Update Customer",
                "parameters": [
                    {
                        "description": "Customer",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Customer"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer Service"
                ],
                "summary": "Create New Customer",
                "parameters": [
                    {
                        "description": "Customer",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Customer"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/customer/validate/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer Service"
                ],
                "summary": "Validate Customer By Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/customer/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer Service"
                ],
                "summary": "Get Customer By Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer Service"
                ],
                "summary": "Delete Customer By Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "types.Address": {
            "type": "object",
            "required": [
                "addressLine",
                "city",
                "cityCode",
                "country"
            ],
            "properties": {
                "addressLine": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "cityCode": {
                    "type": "integer"
                },
                "country": {
                    "type": "string"
                }
            }
        },
        "types.Customer": {
            "type": "object",
            "required": [
                "address",
                "email",
                "name"
            ],
            "properties": {
                "_id": {
                    "type": "string"
                },
                "address": {
                    "$ref": "#/definitions/types.Address"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "143.198.137.31:5000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "User API Documentation",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
